clouseau:
  image:
    pullPolicy: IfNotPresent
    repository: cloudlesshq/clouseau
    tag: latest
logging:
  es:
    host: CHANGEME
    port: 9243
    http_user: elastic
    http_passwd: CHANGEME
    index: minikube
    logstash_prefix: minikube
    tls: "on"
couchdb:
  #adminUsername: jan
  #adminPassword: password
  #cookieAuthSecret: monster
  couchdbConfig:
    chttpd:
      bind_address: any
    httpd:
      bind_address: any
    log:
      level: info
      writer: stdout
  clusterSize: 3
  createAdminSecret: false
  enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: cloudlesshq/couchdb
    # For local testing:
    # pullPolicy: Never
    # repository: couchdb-test
    tag: latest
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/enable-cors: "true"
    hosts:
      - couchdb.local

## Configure 'fluent-bit' subchart
fluent-bit:
  on_minikube: true
  existingConfigMap: fluent-bit-config
  rbac:
    create: false
  serviceAccount:
    name: fluentd-service-account
